### ISSUE TITLE
PRACTICA DE OPERACIONES

### ISSUE THREAD

**Issue by carla1131** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-ghost#1]
[BAUTISTA_LEON_CARLA_PRACTICA.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-ghost/files/12563781/BAUTISTA_LEON_CARLA_PRACTICA.pdf)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 17%
Figuras,ilustraciones y fotografias 25%
Resultados y Clnclusiones 22%                       
Calificacion 17/20                  
Calificado por el equipo de Elisa Sanchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
